## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import gkey

# Configure gmaps API key
gmaps.configure(api_key=gkey)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("weather_data/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Date,Current Description,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Oranjemund,NaN,2022-07-28 03:09:12,clear sky,-28.5500,16.4333,51.94,82,0,0.65
1,1,Guiyang,CN,2022-07-28 03:09:12,broken clouds,26.5833,106.7167,79.09,72,82,2.28
2,2,Arraial Do Cabo,BR,2022-07-28 03:09:13,clear sky,-22.9661,-42.0278,69.64,80,0,23.89
3,3,Albany,US,2022-07-28 03:06:33,overcast clouds,42.6001,-73.9662,70.59,78,92,2.10
4,4,Carballo,ES,2022-07-28 03:04:29,overcast clouds,43.2130,-8.6910,63.91,74,85,1.25

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 78
What is the maximum temperature you would like for your trip? 85

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Current Description,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
1,1,Guiyang,CN,2022-07-28 03:09:12,broken clouds,26.5833,106.7167,79.09,72,82,2.28
14,14,Vaini,TO,2022-07-28 03:09:17,few clouds,-21.2000,-175.2000,78.96,83,20,10.36
19,19,Tripoli,LY,2022-07-28 03:05:19,clear sky,32.8752,13.1875,82.74,47,0,6.82
25,25,Bengkulu,ID,2022-07-28 03:09:20,broken clouds,-3.8004,102.2655,83.39,67,59,1.36
35,35,Tartus,SY,2022-07-28 03:09:23,clear sky,34.8890,35.8866,78.42,61,0,3.38
36,36,Keti Bandar,PK,2022-07-28 03:09:24,broken clouds,24.1447,67.4497,83.52,79,80,12.59
42,42,Katsuura,JP,2022-07-28 03:09:26,broken clouds,35.1333,140.3000,83.19,78,68,12.08
47,47,San Patricio,US,2022-07-28 03:07:50,clear sky,28.0170,-97.5169,84.83,70,4,12.73
58,58,Vasai,IN,2022-07-28 03:10:30,overcast clouds,19.4700,72.8000,80.69,78,100,0.81
69,69,Tommot,RU,2022-07-28 03:10:35,clear sky,58.9564,126.2925,83.07,50,3,7.25

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 1 to 716
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   City_ID              150 non-null    int64
 1   City                 150 non-null    object
 2   Country              150 non-null    object
 3   Date                 150 non-null    object
 4   Current Description  150 non-null    object
 5   Lat                  150 non-null    float64
 6   Lng                  150 non-null    float64
 7   Max Temp             150 non-null    float64
 8   Humidity             150 non-null    int64
 9   Cloudiness           150 non-null    int64
 10  Wind Speed           150 non-null    float64
dtypes: float64(4), int64(3), object(4)
memory usage: 14.1+ KB

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.copy()
clean_df.dropna(how='any', inplace=True)
clean_df

,City_ID,City,Country,Date,Current Description,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
1,1,Guiyang,CN,2022-07-28 03:09:12,broken clouds,26.5833,106.7167,79.09,72,82,2.28
14,14,Vaini,TO,2022-07-28 03:09:17,few clouds,-21.2000,-175.2000,78.96,83,20,10.36
19,19,Tripoli,LY,2022-07-28 03:05:19,clear sky,32.8752,13.1875,82.74,47,0,6.82
25,25,Bengkulu,ID,2022-07-28 03:09:20,broken clouds,-3.8004,102.2655,83.39,67,59,1.36
35,35,Tartus,SY,2022-07-28 03:09:23,clear sky,34.8890,35.8866,78.42,61,0,3.38
...,...,...,...,...,...,...,...,...,...,...,...
692,692,Great Falls,US,2022-07-28 03:26:29,clear sky,47.5002,-111.3008,78.19,37,0,11.50
702,702,Khandyga,RU,2022-07-28 03:28:02,few clouds,62.6667,135.6000,84.60,36,11,3.51
704,704,Veraval,IN,2022-07-28 03:28:03,overcast clouds,20.9000,70.3667,81.81,78,100,6.33
711,711,Thinadhoo,MV,2022-07-28 03:28:05,overcast clouds,0.5333,72.9333,83.17,72,95,13.62
716,716,Marzuq,YE,2022-07-28 03:28:07,overcast clouds,14.4000,46.4667,81.12,43,99,6.02

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Guiyang,CN,79.09,broken clouds,26.5833,106.7167,
14,Vaini,TO,78.96,few clouds,-21.2000,-175.2000,
19,Tripoli,LY,82.74,clear sky,32.8752,13.1875,
25,Bengkulu,ID,83.39,broken clouds,-3.8004,102.2655,
35,Tartus,SY,78.42,clear sky,34.8890,35.8866,
36,Keti Bandar,PK,83.52,broken clouds,24.1447,67.4497,
42,Katsuura,JP,83.19,broken clouds,35.1333,140.3000,
47,San Patricio,US,84.83,clear sky,28.0170,-97.5169,
58,Vasai,IN,80.69,overcast clouds,19.4700,72.8000,
69,Tommot,RU,83.07,clear sky,58.9564,126.2925,

In [8]:
# # Iterate through the DataFrame.
# for index, row in hotel_df.iterrows():
#     # Get the latitude and longitude.
#     lat = row["Lat"]
#     lng = row["Lng"]

#     # Add the latitude and longitude to location key for the params dictionary.
#     params["location"] = f"{lat},{lng}"

#     # Use the search term: "lodging" and our latitude and longitude.
#     base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
#     # Make request and get the JSON data from the search.
#     hotels = requests.get(base_url, params=params).json()
#     # Grab the first hotel from the results and store the name.
#     hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]

In [9]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": gkey
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [10]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna(how='any')
clean_hotel_df

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Guiyang,CN,79.09,broken clouds,26.5833,106.7167,Guo Tai Hotel Guiyang
14,Vaini,TO,78.96,few clouds,-21.2000,-175.2000,Keleti Beach Resort
19,Tripoli,LY,82.74,clear sky,32.8752,13.1875,Al Waddan Hotel
25,Bengkulu,ID,83.39,broken clouds,-3.8004,102.2655,Grage Hotel Bengkulu
35,Tartus,SY,78.42,clear sky,34.8890,35.8866,Mahmoud’s Home
...,...,...,...,...,...,...,...
692,Great Falls,US,78.19,clear sky,47.5002,-111.3008,La Quinta Inn & Suites by Wyndham Great Falls
702,Khandyga,RU,84.60,few clouds,62.6667,135.6000,Apel'sin
704,Veraval,IN,81.81,overcast clouds,20.9000,70.3667,Lords Inn Somnath
711,Thinadhoo,MV,83.17,overcast clouds,0.5333,72.9333,
716,Marzuq,YE,81.12,overcast clouds,14.4000,46.4667,

In [11]:
# 8a. Create the output File (CSV)
output_data_file = "weather_data/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [12]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>

"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [13]:
locations

         Lat       Lng
1    26.5833  106.7167
14  -21.2000 -175.2000
19   32.8752   13.1875
25   -3.8004  102.2655
35   34.8890   35.8866
..       ...       ...
692  47.5002 -111.3008
702  62.6667  135.6000
704  20.9000   70.3667
711   0.5333   72.9333
716  14.4000   46.4667

[150 rows x 2 columns]

In [14]:
hotel_info

['\n<dl>\n<dt>City</dt><dd>Guiyang</dd>\n<dt>Country</dt><dd>CN</dd>\n<dt>Weather Description</dt><dd>broken clouds</dd>\n<dt>Max Temp</dt><dd>79.09 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Vaini</dd>\n<dt>Country</dt><dd>TO</dd>\n<dt>Weather Description</dt><dd>few clouds</dd>\n<dt>Max Temp</dt><dd>78.96 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Tripoli</dd>\n<dt>Country</dt><dd>LY</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>82.74 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Bengkulu</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Weather Description</dt><dd>broken clouds</dd>\n<dt>Max Temp</dt><dd>83.39 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Tartus</dd>\n<dt>Country</dt><dd>SY</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>78.42 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Keti Bandar</dd>\n<dt>Country</dt><dd>PK</dd>\n<dt>Weather Description</dt><dd>broken clouds</dd>\n<dt>Max Temp</dt><dd>83.52 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Katsuura</dd>\n<dt>Country</dt><dd>JP</dd>\n<dt>Weather Description</dt><dd>broken clouds</dd>\n<dt>Max Temp</dt><dd>83.19 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>San Patricio</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>84.83 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Vasai</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>80.69 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Tommot</dd>\n<dt>Country</dt><dd>RU</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>83.07 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Sao Filipe</dd>\n<dt>Country</dt><dd>CV</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>78.17 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Naze</dd>\n<dt>Country</dt><dd>JP</dd>\n<dt>Weather Description</dt><dd>broken clouds</dd>\n<dt>Max Temp</dt><dd>81.48 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Hithadhoo</dd>\n<dt>Country</dt><dd>MV</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>82.42 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Butaritari</dd>\n<dt>Country</dt><dd>KI</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>82.09 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Faanui</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Weather Description</dt><dd>light rain</dd>\n<dt>Max Temp</dt><dd>78.75 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Jalu</dd>\n<dt>Country</dt><dd>LY</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>79.52 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Kapaa</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>light rain</dd>\n<dt>Max Temp</dt><dd>84.18 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Summerville</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>82.89 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Qalyub</dd>\n<dt>Country</dt><dd>EG</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>79.59 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Noumea</dd>\n<dt>Country</dt><dd>NC</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>78.78 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Male</dd>\n<dt>Country</dt><dd>MV</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>82.38 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Kitimat</dd>\n<dt>Country</dt><dd>CA</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>83.91 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Oistins</dd>\n<dt>Country</dt><dd>BB</dd>\n<dt>Weather Description</dt><dd>scattered clouds</dd>\n<dt>Max Temp</dt><dd>80.69 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Marsh Harbour</dd>\n<dt>Country</dt><dd>BS</dd>\n<dt>Weather Description</dt><dd>scattered clouds</dd>\n<dt>Max Temp</dt><dd>82.2 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Kavieng</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Weather Description</dt><dd>light rain</dd>\n<dt>Max Temp</dt><dd>84.92 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Liberty</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>83.26 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Fairview</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>79.23 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Baghdad</dd>\n<dt>Country</dt><dd>IQ</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>78.71 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Litovko</dd>\n<dt>Country</dt><dd>RU</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>80.62 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Darab</dd>\n<dt>Country</dt><dd>IR</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>79.77 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Dunhua</dd>\n<dt>Country</dt><dd>CN</dd>\n<dt>Weather Description</dt><dd>light rain</dd>\n<dt>Max Temp</dt><dd>81.36 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Bathsheba</dd>\n<dt>Country</dt><dd>BB</dd>\n<dt>Weather Description</dt><dd>scattered clouds</dd>\n<dt>Max Temp</dt><dd>81.21 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Hambantota</dd>\n<dt>Country</dt><dd>LK</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>80.51 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Zhigansk</dd>\n<dt>Country</dt><dd>RU</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>78.35 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Viransehir</dd>\n<dt>Country</dt><dd>TR</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>83.97 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Mehriz</dd>\n<dt>Country</dt><dd>IR</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>82.9 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Srivardhan</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>80.29 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Karratha</dd>\n<dt>Country</dt><dd>AU</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>79.48 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Manokwari</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Weather Description</dt><dd>broken clouds</dd>\n<dt>Max Temp</dt><dd>84.29 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Tomas Oppus</dd>\n<dt>Country</dt><dd>PH</dd>\n<dt>Weather Description</dt><dd>scattered clouds</dd>\n<dt>Max Temp</dt><dd>84.85 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Mount Vernon</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>broken clouds</dd>\n<dt>Max Temp</dt><dd>79.02 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Eydhafushi</dd>\n<dt>Country</dt><dd>MV</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>82.04 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Sorong</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Weather Description</dt><dd>scattered clouds</dd>\n<dt>Max Temp</dt><dd>81.72 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Sola</dd>\n<dt>Country</dt><dd>VU</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>79.88 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Lazaro Cardenas</dd>\n<dt>Country</dt><dd>MX</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>80.42 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Agua Dulce</dd>\n<dt>Country</dt><dd>MX</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>78.37 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Kavaratti</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Weather Description</dt><dd>heavy intensity rain</dd>\n<dt>Max Temp</dt><dd>78.17 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Trairi</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>78.33 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Vanderhoof</dd>\n<dt>Country</dt><dd>CA</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>82.67 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Meulaboh</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>81.95 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Port Blair</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Weather Description</dt><dd>broken clouds</dd>\n<dt>Max Temp</dt><dd>84.24 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Daru</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Weather Description</dt><dd>scattered clouds</dd>\n<dt>Max Temp</dt><dd>78.15 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Estelle</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>scattered clouds</dd>\n<dt>Max Temp</dt><dd>84.2 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Misratah</dd>\n<dt>Country</dt><dd>LY</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>80.53 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Gouyave</dd>\n<dt>Country</dt><dd>GD</dd>\n<dt>Weather Description</dt><dd>scattered clouds</dd>\n<dt>Max Temp</dt><dd>79.57 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Houma</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>79.0 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Vanimo</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Weather Description</dt><dd>broken clouds</dd>\n<dt>Max Temp</dt><dd>84.85 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Weihe</dd>\n<dt>Country</dt><dd>CN</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>82.27 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Kahului</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>few clouds</dd>\n<dt>Max Temp</dt><dd>84.22 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Umm Lajj</dd>\n<dt>Country</dt><dd>SA</dd>\n<dt>Weather Description</dt><dd>scattered clouds</dd>\n<dt>Max Temp</dt><dd>84.51 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Mangrol</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>81.86 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Acajutla</dd>\n<dt>Country</dt><dd>SV</dd>\n<dt>Weather Description</dt><dd>broken clouds</dd>\n<dt>Max Temp</dt><dd>79.02 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Sangar</dd>\n<dt>Country</dt><dd>RU</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>81.03 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Acarau</dd>\n<dt>Country</dt><dd>BR</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>78.58 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Karaton</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>80.29 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Biak</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>80.22 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Katherine</dd>\n<dt>Country</dt><dd>AU</dd>\n<dt>Weather Description</dt><dd>few clouds</dd>\n<dt>Max Temp</dt><dd>80.92 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Praia</dd>\n<dt>Country</dt><dd>CV</dd>\n<dt>Weather Description</dt><dd>few clouds</dd>\n<dt>Max Temp</dt><dd>79.34 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Fare</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Weather Description</dt><dd>light rain</dd>\n<dt>Max Temp</dt><dd>78.35 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Russell</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>82.0 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Mayo</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>82.35 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Balaipungut</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Weather Description</dt><dd>broken clouds</dd>\n<dt>Max Temp</dt><dd>84.9 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Zhengjiatun</dd>\n<dt>Country</dt><dd>CN</dd>\n<dt>Weather Description</dt><dd>light rain</dd>\n<dt>Max Temp</dt><dd>81.84 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Kloulklubed</dd>\n<dt>Country</dt><dd>PW</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>84.7 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Latung</dd>\n<dt>Country</dt><dd>PH</dd>\n<dt>Weather Description</dt><dd>broken clouds</dd>\n<dt>Max Temp</dt><dd>83.19 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Waingapu</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Weather Description</dt><dd>scattered clouds</dd>\n<dt>Max Temp</dt><dd>83.52 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Todos Santos</dd>\n<dt>Country</dt><dd>MX</dd>\n<dt>Weather Description</dt><dd>scattered clouds</dd>\n<dt>Max Temp</dt><dd>81.05 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Wattegama</dd>\n<dt>Country</dt><dd>LK</dd>\n<dt>Weather Description</dt><dd>heavy intensity rain</dd>\n<dt>Max Temp</dt><dd>81.18 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Ray</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>83.17 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Lorengau</dd>\n<dt>Country</dt><dd>PG</dd>\n<dt>Weather Description</dt><dd>scattered clouds</dd>\n<dt>Max Temp</dt><dd>83.88 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Bireun</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>82.2 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Yatou</dd>\n<dt>Country</dt><dd>CN</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>80.26 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Cartagena</dd>\n<dt>Country</dt><dd>CO</dd>\n<dt>Weather Description</dt><dd>broken clouds</dd>\n<dt>Max Temp</dt><dd>80.22 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Solnechnyy</dd>\n<dt>Country</dt><dd>RU</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>80.46 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Muli</dd>\n<dt>Country</dt><dd>MV</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>82.53 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Vaitape</dd>\n<dt>Country</dt><dd>PF</dd>\n<dt>Weather Description</dt><dd>light rain</dd>\n<dt>Max Temp</dt><dd>78.73 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Muroto</dd>\n<dt>Country</dt><dd>JP</dd>\n<dt>Weather Description</dt><dd>broken clouds</dd>\n<dt>Max Temp</dt><dd>82.76 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Tual</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Weather Description</dt><dd>scattered clouds</dd>\n<dt>Max Temp</dt><dd>79.14 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Bargi</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>81.37 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Hosakote</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Weather Description</dt><dd>broken clouds</dd>\n<dt>Max Temp</dt><dd>79.81 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Jasper</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>79.38 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Prachuap Khiri Khan</dd>\n<dt>Country</dt><dd>TH</dd>\n<dt>Weather Description</dt><dd>moderate rain</dd>\n<dt>Max Temp</dt><dd>83.59 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Kharan</dd>\n<dt>Country</dt><dd>PK</dd>\n<dt>Weather Description</dt><dd>moderate rain</dd>\n<dt>Max Temp</dt><dd>84.16 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Shahrud</dd>\n<dt>Country</dt><dd>IR</dd>\n<dt>Weather Description</dt><dd>broken clouds</dd>\n<dt>Max Temp</dt><dd>78.15 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Baracoa</dd>\n<dt>Country</dt><dd>CU</dd>\n<dt>Weather Description</dt><dd>broken clouds</dd>\n<dt>Max Temp</dt><dd>79.07 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Kirakira</dd>\n<dt>Country</dt><dd>SB</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>83.32 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>San Andres</dd>\n<dt>Country</dt><dd>CO</dd>\n<dt>Weather Description</dt><dd>scattered clouds</dd>\n<dt>Max Temp</dt><dd>82.42 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Lahaina</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>84.2 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Lander</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>moderate rain</dd>\n<dt>Max Temp</dt><dd>79.2 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Siva</dd>\n<dt>Country</dt><dd>EG</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>81.54 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Agadez</dd>\n<dt>Country</dt><dd>NE</dd>\n<dt>Weather Description</dt><dd>scattered clouds</dd>\n<dt>Max Temp</dt><dd>84.81 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Makakilo City</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>82.72 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Santa Cruz Del Sur</dd>\n<dt>Country</dt><dd>CU</dd>\n<dt>Weather Description</dt><dd>broken clouds</dd>\n<dt>Max Temp</dt><dd>78.89 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Bubaque</dd>\n<dt>Country</dt><dd>GW</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>79.93 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Coahuayana</dd>\n<dt>Country</dt><dd>MX</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>78.4 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Myrtle Beach</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>82.44 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Jacksonville Beach</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>few clouds</dd>\n<dt>Max Temp</dt><dd>80.73 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Nabire</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Weather Description</dt><dd>few clouds</dd>\n<dt>Max Temp</dt><dd>82.36 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Baturaja</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>78.66 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Batesville</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>scattered clouds</dd>\n<dt>Max Temp</dt><dd>83.84 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Saint Marys</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>80.71 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Bocas Del Toro</dd>\n<dt>Country</dt><dd>PA</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>78.98 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Champerico</dd>\n<dt>Country</dt><dd>GT</dd>\n<dt>Weather Description</dt><dd>broken clouds</dd>\n<dt>Max Temp</dt><dd>79.18 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Dwarka</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>82.71 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Kualakapuas</dd>\n<dt>Country</dt><dd>ID</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>84.47 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Tezu</dd>\n<dt>Country</dt><dd>IN</dd>\n<dt>Weather Description</dt><dd>overcast clouds</dd>\n<dt>Max Temp</dt><dd>78.28 °F</dd>\n</dl>\n\n',
 '\n<dl>\n<dt>City</dt><dd>Nanakuli</dd>\n<dt>Country</dt><dd>US</dd>\n<dt>Weather Description</dt><dd>clear sky</dd>\n<dt>Max Temp</dt><dd>84.15 °F</dd>\n</dl>\n\n',

In [15]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

#11b. Add a marker
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
# fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11c. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))